import React from "react";
import { BadgeType } from "../types";
import { Database, Sparkles, Sliders, Radio } from "lucide-react";

interface MetricBadgeProps {
  type: BadgeType | string;
  className?: string;
  showIcon?: boolean;
}

export const MetricBadge: React.FC<MetricBadgeProps> = ({
  type,
  className = "",
  showIcon = true
}) => {
  switch (type) {
    case "DATASET":
      return (
        <span
          className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-[11px] font-semibold tracking-wide uppercase bg-blue-50 text-blue-700 border border-blue-200 dark:bg-blue-950/50 dark:text-blue-300 dark:border-blue-800 ${className}`}
          title="Directly derived from authentic historical training records"
        >
          {showIcon && <Database className="w-3 h-3 text-blue-600 dark:text-blue-400" />}
          DATASET
        </span>
      );
    case "PREDICTION":
      return (
        <span
          className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-[11px] font-semibold tracking-wide uppercase bg-emerald-50 text-emerald-700 border border-emerald-200 dark:bg-emerald-950/50 dark:text-emerald-300 dark:border-emerald-800 ${className}`}
          title="Generated by trained Machine Learning models (ML estimate, not guarantee)"
        >
          {showIcon && <Sparkles className="w-3 h-3 text-emerald-600 dark:text-emerald-400" />}
          PREDICTION
        </span>
      );
    case "ESTIMATE":
      return (
        <span
          className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-[11px] font-semibold tracking-wide uppercase bg-amber-50 text-amber-800 border border-amber-200 dark:bg-amber-950/50 dark:text-amber-300 dark:border-amber-800 ${className}`}
          title="Statistical calculation / 95% confidence interval based on residual error"
        >
          {showIcon && <Sliders className="w-3 h-3 text-amber-600 dark:text-amber-400" />}
          ESTIMATE
        </span>
      );
    case "LIVE API":
    default:
      return (
        <span
          className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-[11px] font-semibold tracking-wide uppercase bg-rose-50 text-rose-700 border border-rose-200 dark:bg-rose-950/50 dark:text-rose-300 dark:border-rose-800 ${className}`}
          title="External sensor API stream (Currently disconnected)"
        >
          {showIcon && <Radio className="w-3 h-3 text-rose-600 dark:text-rose-400" />}
          LIVE API
        </span>
      );
  }
};
